services:
  postgres:
    image:
      postgres:14.12
    environment:
      POSTGRES_DB: "movie_api"
      POSTGRES_USER: "movie_api"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d